services:
  - type: web
    name: wheretohoop
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: playwright install chromium && gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
